Repository URECA-Cookie/Cookie-BE, pull requests merged in 2024-11, with the labels that each got.

#2 Feat: 프로젝트 구조 정의 및 엔티티 설계
  cookie/src/main/java/com/cookie/domain/actor/entity/Actor.java
  cookie/src/main/java/com/cookie/domain/badge/entity/Badge.java
  cookie/src/main/java/com/cookie/domain/badge/entity/Grade.java
  cookie/src/main/java/com/cookie/domain/category/entity/Category.java
  cookie/src/main/java/com/cookie/domain/chat/entity/Chatroom.java
  cookie/src/main/java/com/cookie/domain/country/entity/Country.java
  cookie/src/main/java/com/cookie/domain/director/entity/Director.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/CharmPoint.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/EmotionPoint.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/MatchUp.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/MatchUpStatus.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/MatchUpType.java
  cookie/src/main/java/com/cookie/domain/movie/entity/Movie.java
  cookie/src/main/java/com/cookie/domain/movie/entity/MovieActor.java
  cookie/src/main/java/com/cookie/domain/movie/entity/MovieCategory.java
  cookie/src/main/java/com/cookie/domain/movie/entity/MovieCountry.java
  cookie/src/main/java/com/cookie/domain/movie/entity/MovieDirector.java
  cookie/src/main/java/com/cookie/domain/movie/entity/MovieImage.java
  cookie/src/main/java/com/cookie/domain/movie/entity/MovieLike.java
  cookie/src/main/java/com/cookie/domain/movie/entity/MovieVideo.java
  cookie/src/main/java/com/cookie/domain/movie/entity/Rating.java
  cookie/src/main/java/com/cookie/domain/review/entity/Review.java
  cookie/src/main/java/com/cookie/domain/review/entity/ReviewComment.java
  cookie/src/main/java/com/cookie/domain/review/entity/ReviewLike.java
  cookie/src/main/java/com/cookie/domain/user/entity/BadgePoint.java
  cookie/src/main/java/com/cookie/domain/user/entity/GenreScore.java
  cookie/src/main/java/com/cookie/domain/user/entity/MatchUpParticipation.java
  cookie/src/main/java/com/cookie/domain/user/entity/Role.java
  cookie/src/main/java/com/cookie/domain/user/entity/SocialProvider.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/entity/UserBadge.java
  cookie/src/main/java/com/cookie/domain/user/entity/UserCategory.java
  cookie/src/main/java/com/cookie/domain/user/entity/UserChatroom.java
  cookie/src/main/java/com/cookie/global/common/entity/CommonCode.java
  cookie/src/main/java/com/cookie/global/common/entity/CommonCodeGroup.java
  cookie/src/main/java/com/cookie/global/config/JpaAuditingConfig.java
  cookie/src/main/java/com/cookie/global/entity/BaseTimeEntity.java
Labels: 🍿 Feat

#11 Feat: 영화 리뷰 시스템
  cookie/src/main/java/com/cookie/domain/movie/controller/MovieController.java
  cookie/src/main/java/com/cookie/domain/movie/dto/response/ReviewMovieResponse.java
  cookie/src/main/java/com/cookie/domain/movie/dto/response/ReviewOfMovieResponse.java
  cookie/src/main/java/com/cookie/domain/movie/entity/Movie.java
  cookie/src/main/java/com/cookie/domain/movie/repository/MovieCategoryRepository.java
  cookie/src/main/java/com/cookie/domain/movie/repository/MovieCountryRepository.java
  cookie/src/main/java/com/cookie/domain/movie/repository/MovieRepository.java
  cookie/src/main/java/com/cookie/domain/movie/service/MovieService.java
  cookie/src/main/java/com/cookie/domain/review/controller/ReviewController.java
  cookie/src/main/java/com/cookie/domain/review/dto/request/CreateReviewRequest.java
  cookie/src/main/java/com/cookie/domain/review/dto/request/ReviewCommentRequest.java
  cookie/src/main/java/com/cookie/domain/review/dto/request/UpdateReviewRequest.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/MovieReviewResponse.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/ReviewCommentResponse.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/ReviewDetailResponse.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/ReviewResponse.java
  cookie/src/main/java/com/cookie/domain/review/entity/Review.java
  cookie/src/main/java/com/cookie/domain/review/entity/ReviewComment.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewCommentRepository.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewLikeRepository.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewRepository.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/CommentUserResponse.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/MovieReviewUserResponse.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/ReviewUserResponse.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/repository/UserRepository.java
Labels: ✅ wontfix, 🍿 Feat

#16 Feat: CORS 설정
  cookie/src/main/java/com/cookie/global/config/CorsMvcConfig.java
Labels: 🍿 Feat

#14 Feat: 스프링 시큐리티 세팅 및 OAuth2 소셜 로그인 구현
  cookie/build.gradle
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/dto/request/RegisterRequest.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/CustomOAuth2User.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/GoogleResponse.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/NaverResponse.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/OAuth2Response.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/OAuth2UserResponse.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/RegisterResponse.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/RegistrationRequiredResponse.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/repository/UserRepository.java
  cookie/src/main/java/com/cookie/domain/user/service/CustomOAuth2UserService.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
  cookie/src/main/java/com/cookie/global/config/SecurityConfig.java
  cookie/src/main/java/com/cookie/global/jwt/JWTFilter.java
  cookie/src/main/java/com/cookie/global/jwt/JWTUtil.java
  cookie/src/main/java/com/cookie/global/oauth/CustomSuccessHandler.java
Labels: 🍿 Feat, 🚀 Refactor

#24 Feat: 관리자 회원가입 및 로그인 기능 구현
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/dto/request/auth/AdminLoginRequest.java
  cookie/src/main/java/com/cookie/domain/user/dto/request/auth/AdminRegisterRequest.java
  cookie/src/main/java/com/cookie/domain/user/dto/request/auth/RegisterRequest.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/repository/UserRepository.java
  cookie/src/main/java/com/cookie/domain/user/service/CustomUserDetailsService.java
  cookie/src/main/java/com/cookie/global/config/SecurityConfig.java
  cookie/src/main/java/com/cookie/global/jwt/JWTUtil.java
  cookie/src/main/java/com/cookie/global/oauth/CustomSuccessHandler.java
Labels: 🍿 Feat, 🚀 Refactor

#27 Feat: JWT Refresh Token 구현
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/TokenResponse.java
  cookie/src/main/java/com/cookie/domain/user/service/CustomOAuth2UserService.java
  cookie/src/main/java/com/cookie/global/config/SecurityConfig.java
  cookie/src/main/java/com/cookie/global/jwt/JWTFilter.java
  cookie/src/main/java/com/cookie/global/jwt/JWTUtil.java
  cookie/src/main/java/com/cookie/global/oauth/CustomSuccessHandler.java
Labels: 🍿 Feat, 🚀 Refactor

#20 Feat: 영화 매치업 조회 및 투표 시스템
  cookie/src/main/java/com/cookie/domain/matchup/controller/MatchUpController.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/request/CharmPointRequest.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/request/EmotionPointRequest.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/request/MatchUpVoteRequest.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/CharmPointResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/EmotionPointResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/MatchUpHistoryDetailResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/MatchUpHistoryResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/MatchUpMovieResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/MatchUpResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/CharmPoint.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/EmotionPoint.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/MatchUp.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/MatchUpMovie.java
  cookie/src/main/java/com/cookie/domain/matchup/repository/MatchUpMovieRepository.java
  cookie/src/main/java/com/cookie/domain/matchup/repository/MatchUpRepository.java
  cookie/src/main/java/com/cookie/domain/matchup/service/MatchUpService.java
  cookie/src/main/java/com/cookie/domain/user/entity/MatchUpParticipation.java
  cookie/src/main/java/com/cookie/domain/user/repository/MatchUpParticipationRepository.java
Labels: 🍿 Feat

#28 Refactor: 영화 리뷰 시스템 리팩토링
  cookie/src/main/java/com/cookie/domain/movie/controller/MovieController.java
  cookie/src/main/java/com/cookie/domain/movie/service/MovieService.java
  cookie/src/main/java/com/cookie/domain/review/controller/ReviewController.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/MovieReviewResponse.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/ReviewDetailResponse.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/ReviewResponse.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewLikeRepository.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewRepository.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
Labels: 🍿 Feat, 🚀 Refactor

#31 Feat: AWS S3 이미지 업로드 구현
  cookie/build.gradle
  cookie/src/main/java/com/cookie/global/config/AWSS3Config.java
  cookie/src/main/java/com/cookie/global/controller/AWSS3Controller.java
  cookie/src/main/java/com/cookie/global/service/AWSS3Service.java
Labels: 🍿 Feat

#33 Refactor: 회원가입 시 선호 장르 데이터 저장 구현
  cookie/src/main/java/com/cookie/domain/category/service/CategoryService.java
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/dto/request/auth/RegisterRequest.java
  cookie/src/main/java/com/cookie/domain/user/entity/GenreScore.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/service/GenreScoreService.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
  cookie/src/main/java/com/cookie/global/oauth/CustomSuccessHandler.java
Labels: 🍿 Feat, 🚀 Refactor

#36 Feat: 회원가입 시 사진 파일을 포함해 처리할 수 있도록 기능 추가
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
Labels: 🍿 Feat

#37 Refactor: 영화 리뷰 시스템 페이지네이션 적용
  cookie/src/main/java/com/cookie/domain/movie/controller/MovieController.java
  cookie/src/main/java/com/cookie/domain/movie/dto/response/ReviewOfMovieResponse.java
  cookie/src/main/java/com/cookie/domain/movie/service/MovieService.java
  cookie/src/main/java/com/cookie/domain/review/controller/ReviewController.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/ReviewListResponse.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewRepository.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
Labels: 🍿 Feat, 🚀 Refactor

#39 Feat: 영화, 배우, 감독 검색 기능 구현
  cookie/src/main/java/com/cookie/domain/actor/repository/ActorRepository.java
  cookie/src/main/java/com/cookie/domain/director/repository/DirectorRepository.java
  cookie/src/main/java/com/cookie/domain/movie/repository/MovieRepository.java
  cookie/src/main/java/com/cookie/domain/search/controller/SearchController.java
  cookie/src/main/java/com/cookie/domain/search/dto/request/SearchRequest.java
  cookie/src/main/java/com/cookie/domain/search/dto/response/SearchResponse.java
  cookie/src/main/java/com/cookie/domain/search/service/SearchService.java
Labels: 🍿 Feat

#51 Feat: 로그인 유저 id 정보 얻을 수 있도록 수정
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/CustomOAuth2User.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/CustomUserDetails.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/auth/OAuth2UserResponse.java
  cookie/src/main/java/com/cookie/domain/user/service/CustomOAuth2UserService.java
  cookie/src/main/java/com/cookie/domain/user/service/CustomUserDetailsService.java
  cookie/src/main/java/com/cookie/global/jwt/JWTFilter.java
  cookie/src/main/java/com/cookie/global/jwt/JWTUtil.java
  cookie/src/main/java/com/cookie/global/oauth/CustomSuccessHandler.java
Labels: 🍿 Feat, 🚀 Refactor

#49 Feat: 매치업 채팅 기본 작업
  cookie/build.gradle
  cookie/src/main/java/com/cookie/domain/matchup/controller/ChatController.java
  cookie/src/main/java/com/cookie/domain/matchup/controller/ChatMessageController.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/request/ChatMessageRequest.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/ChatMessageResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/ChatMessage.java
  cookie/src/main/java/com/cookie/domain/matchup/repository/ChatMessageRepository.java
  cookie/src/main/java/com/cookie/domain/matchup/service/ChatService.java
  cookie/src/main/java/com/cookie/global/config/SecurityConfig.java
  cookie/src/main/java/com/cookie/global/config/WebSocketConfig.java
Labels: 🍿 Feat

#53 Feat: 매치업 진행 관리 구현
  cookie/src/main/java/com/cookie/CookieApplication.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/MainMatchUpsResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/MatchUp.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/MatchUpMovie.java
  cookie/src/main/java/com/cookie/domain/matchup/entity/enums/MatchUpStatus.java
  cookie/src/main/java/com/cookie/domain/matchup/repository/MatchUpRepository.java
  cookie/src/main/java/com/cookie/domain/matchup/scheduler/MatchUpScheduler.java
  cookie/src/main/java/com/cookie/domain/matchup/service/MatchUpService.java
Labels: 🍿 Feat

#42 Feat: push 알림 기능 구현
  cookie/src/main/java/com/cookie/domain/movie/repository/MovieRepository.java
  cookie/src/main/java/com/cookie/domain/review/controller/ReviewController.java
  cookie/src/main/java/com/cookie/domain/review/dto/response/PushNotification.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/controller/UserController.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/repository/UserRepository.java
Labels: 🍿 Feat

#60 Refactor: 숨김 처리된 리뷰 제외하고 반환하도록 수정
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewRepository.java
Labels: 🚀 Refactor

#62 Feat: 마이페이지 리팩토링
  cookie/src/main/java/com/cookie/domain/user/controller/UserController.java
  cookie/src/main/java/com/cookie/domain/user/dto/request/MyProfileRequest.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/entity/UserBadge.java
  cookie/src/main/java/com/cookie/domain/user/entity/UserCategory.java
  cookie/src/main/java/com/cookie/domain/user/repository/UserRepository.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
Labels: 🍿 Feat, 🚀 Refactor

#67 Fix: 마이페이지 누락된 기능 추가 및 수정
  cookie/src/main/java/com/cookie/domain/movie/entity/Movie.java
  cookie/src/main/java/com/cookie/domain/review/controller/ReviewController.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewLikeRepository.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/controller/UserController.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/MyProfileDataResponse.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
Labels: 🍿 Feat, ⚒️ Fix

#70 Fix: 회원가입 시 닉네임 중복체크에서 인증된 사용자 제외
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
Labels: ⚒️ Fix
