Repository URECA-Cookie/Cookie-BE, pull requests merged in 2024-12, with the labels that each got.

#71 Update SecurityConfig.java
  cookie/src/main/java/com/cookie/global/config/SecurityConfig.java
Labels: 🍿 Feat

#65 Feat: 영화 리뷰 시스템 관련 메서드 인증된 사용자 정보 활용
  cookie/src/main/java/com/cookie/domain/movie/controller/MovieController.java
  cookie/src/main/java/com/cookie/domain/review/controller/ReviewController.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/CommentUserResponse.java
  cookie/src/main/java/com/cookie/global/config/SecurityConfig.java
  cookie/src/main/java/com/cookie/global/config/WebConfig.java
  cookie/src/test/java/com/cookie/domain/review/service/ReviewServiceTest.java
Labels: 🍿 Feat, 😾 Test

#75 Feat: 매치업 시스템 인증된 사용자 정보 활용
  cookie/src/main/java/com/cookie/domain/matchup/controller/ChatMessageController.java
  cookie/src/main/java/com/cookie/domain/matchup/controller/MatchUpController.java
  cookie/src/main/java/com/cookie/domain/matchup/interceptor/JwtChannelInterceptor.java
  cookie/src/main/java/com/cookie/domain/movie/service/MovieService.java
  cookie/src/main/java/com/cookie/global/config/SecurityConfig.java
  cookie/src/main/java/com/cookie/global/config/WebSocketConfig.java
Labels: 🍿 Feat

#82 Feat: 회원가입 시 유저 정보 반환 추가
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/controller/UserController.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/UserInfoResponse.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/UserResponse.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
Labels: ✅ wontfix, 🍿 Feat

#94 Refactor: 영화 메소드 인증된 사용자만 접근 가능하도록 수정
  cookie/src/main/java/com/cookie/domain/movie/controller/MovieController.java
  cookie/src/main/java/com/cookie/domain/movie/dto/response/MovieResponse.java
  cookie/src/main/java/com/cookie/domain/movie/service/MovieService.java
  cookie/src/main/java/com/cookie/global/config/CacheConfig.java
Labels: 🚀 Refactor

#99 Fix: 영화 검색 시 무한루프 오류 수정 및 제대로 된 응답 데이터를 반환하도록 수정
  cookie/src/main/java/com/cookie/domain/actor/repository/ActorRepository.java
  cookie/src/main/java/com/cookie/domain/director/repository/DirectorRepository.java
  cookie/src/main/java/com/cookie/domain/movie/repository/MovieRepository.java
  cookie/src/main/java/com/cookie/domain/search/controller/SearchController.java
  cookie/src/main/java/com/cookie/domain/search/dto/request/SearchRequest.java
  cookie/src/main/java/com/cookie/domain/search/dto/response/SearchMovieResponse.java
  cookie/src/main/java/com/cookie/domain/search/dto/response/SearchResponse.java
  cookie/src/main/java/com/cookie/domain/search/service/SearchService.java
Labels: 👿 Bug, 🍿 Feat, ⚒️ Fix

#87 Feat: FCM 푸쉬알림 Basic
  cookie/.gitignore
  cookie/build.gradle
  cookie/src/main/java/com/cookie/domain/category/entity/Category.java
  cookie/src/main/java/com/cookie/domain/notification/NotificationInitializer.java
  cookie/src/main/java/com/cookie/domain/notification/config/FirebaseConfig.java
  cookie/src/main/java/com/cookie/domain/notification/controller/NotificationController.java
  cookie/src/main/java/com/cookie/domain/notification/dto/request/FcmTokenRequest.java
  cookie/src/main/java/com/cookie/domain/notification/entity/FcmToken.java
  cookie/src/main/java/com/cookie/domain/notification/repository/FcmTokenRepository.java
  cookie/src/main/java/com/cookie/domain/notification/service/FcmTokenService.java
  cookie/src/main/java/com/cookie/domain/notification/service/NotificationService.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
Labels: 🍿 Feat

#103 Feature/#100 CI CD
  cookie/.github/workflows/deploy.yml
  cookie/build.gradle
  cookie/src/main/java/com/cookie/admin/service/movie/TMDBService.java
  cookie/src/main/java/com/cookie/domain/movie/controller/MovieController.java
Labels: 🍿 Feat, 🚀 Refactor

#110 Fix: #109 CI/CD 테스트 1
  cookie/.github/workflows/deploy.yml
Labels: ⚒️ Fix

#111 Fix: #109 CI/CD 테스트 2
  cookie/.github/workflows/deploy.yml
Labels: ⚒️ Fix

#112 Fix: #109 CI/CD 테스트 3
  cookie/.github/workflows/deploy.yml
Labels: ⚒️ Fix

#83 Feat: 영화 평점 갱신 구현
  cookie/src/main/java/com/cookie/domain/movie/entity/Movie.java
  cookie/src/main/java/com/cookie/domain/movie/scheduler/MovieRatingScheduler.java
  cookie/src/main/java/com/cookie/domain/movie/service/MovieRatingService.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewRepository.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
Labels: 🍿 Feat

#121 Fix: 회원가입 버그 수정 작업
  cookie/src/main/java/com/cookie/domain/user/controller/AuthController.java
  cookie/src/main/java/com/cookie/domain/user/controller/UserController.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
  cookie/src/main/java/com/cookie/global/exception/handler/GlobalExceptionHandler.java
  cookie/src/main/java/com/cookie/global/service/AWSS3Service.java
Labels: 🚀 Refactor, ⚒️ Fix

#124 Feature/#78 reward history
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/reward/entity/RewardHistory.java
  cookie/src/main/java/com/cookie/domain/reward/repository/RewardHistoryRepository.java
  cookie/src/main/java/com/cookie/domain/reward/service/RewardHistoryService.java
  cookie/src/main/java/com/cookie/domain/reward/service/RewardPointService.java
  cookie/src/main/java/com/cookie/domain/user/controller/UserController.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/MyBadgeHistoryResponse.java
  cookie/src/main/java/com/cookie/domain/user/dto/response/MyPageResponse.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
  cookie/src/main/java/com/cookie/global/jwt/JWTUtil.java
Labels: 🍿 Feat, 🚀 Refactor

#127 Feature/#125 match up point
  cookie/src/main/java/com/cookie/domain/matchup/batch/MatchUpCloseBatch.java
  cookie/src/main/java/com/cookie/domain/matchup/dto/response/MatchUpCloseResponse.java
  cookie/src/main/java/com/cookie/domain/matchup/scheduler/MatchUpScheduler.java
  cookie/src/main/java/com/cookie/domain/matchup/service/MatchUpService.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/reward/service/RewardCacheService.java
  cookie/src/main/java/com/cookie/domain/reward/service/RewardPointService.java
  cookie/src/main/java/com/cookie/domain/user/repository/MatchUpParticipationRepository.java
Labels: 🍿 Feat, 🚀 Refactor

#123 Feature/#122 push notification settings
  cookie/build.gradle
  cookie/src/main/java/com/cookie/domain/notification/controller/NotificationController.java
  cookie/src/main/java/com/cookie/domain/notification/dto/request/NotificationReadRequest.java
  cookie/src/main/java/com/cookie/domain/notification/dto/request/NotificationRequest.java
  cookie/src/main/java/com/cookie/domain/notification/dto/response/NotificationResponse.java
  cookie/src/main/java/com/cookie/domain/notification/entity/enums/Status.java
  cookie/src/main/java/com/cookie/domain/notification/repository/FcmTokenRepository.java
  cookie/src/main/java/com/cookie/domain/notification/scheduler/NotificationScheduler.java
  cookie/src/main/java/com/cookie/domain/notification/service/FcmTokenService.java
  cookie/src/main/java/com/cookie/domain/notification/service/NotificationService.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/entity/User.java
  cookie/src/main/java/com/cookie/domain/user/service/UserService.java
  cookie/src/main/java/com/cookie/global/config/RedisConfig.java
Labels: 🍿 Feat

#132 Refactor: 영화 검색 시 LIKE 조건을 수정하여 인덱스 활용 최적화
  cookie/src/main/java/com/cookie/domain/movie/repository/MovieRepository.java
  cookie/src/main/java/com/cookie/domain/search/dto/response/SearchMovieResponse.java
  cookie/src/main/java/com/cookie/domain/search/service/SearchService.java
Labels: 🚀 Refactor

#137 Feature/#136 movie review like feed
  cookie/src/main/java/com/cookie/domain/movie/controller/MovieController.java
  cookie/src/main/java/com/cookie/domain/movie/service/MovieService.java
  cookie/src/main/java/com/cookie/domain/review/repository/ReviewRepository.java
  cookie/src/main/java/com/cookie/global/config/SecurityConfig.java
Labels: 🍿 Feat, 🚀 Refactor

#139 Refactor: 리뷰 생성 메소드 불필요한 코드 제거
  cookie/src/main/java/com/cookie/domain/review/controller/ReviewController.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/repository/UserRepository.java
Labels: 🚀 Refactor

#145 Fix: FCM 토큰 중복 오류 수정
  cookie/src/main/java/com/cookie/domain/notification/service/FcmTokenService.java
  cookie/src/main/java/com/cookie/domain/notification/service/NotificationService.java
  cookie/src/main/java/com/cookie/domain/review/service/ReviewService.java
  cookie/src/main/java/com/cookie/domain/user/repository/UserRepository.java
Labels: ⚒️ Fix
